// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWQtv910LSQLpHLh_QkfT2blPw7anpIms',
    appId: '1:938205689320:web:8ac9f15fbc58a298eee05d',
    messagingSenderId: '938205689320',
    projectId: 'examflutter-9bb0e',
    authDomain: 'examflutter-9bb0e.firebaseapp.com',
    storageBucket: 'examflutter-9bb0e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByOR6YqqYemWWU_zR82Xgd4QKDo3HFEzI',
    appId: '1:938205689320:android:ac41ca24e4343621eee05d',
    messagingSenderId: '938205689320',
    projectId: 'examflutter-9bb0e',
    storageBucket: 'examflutter-9bb0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2rVa8Ng9BMTkJzzkVaaPIA_fTlYmgwvo',
    appId: '1:938205689320:ios:3909314b71829020eee05d',
    messagingSenderId: '938205689320',
    projectId: 'examflutter-9bb0e',
    storageBucket: 'examflutter-9bb0e.appspot.com',
    iosBundleId: 'com.example.flutterExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2rVa8Ng9BMTkJzzkVaaPIA_fTlYmgwvo',
    appId: '1:938205689320:ios:3909314b71829020eee05d',
    messagingSenderId: '938205689320',
    projectId: 'examflutter-9bb0e',
    storageBucket: 'examflutter-9bb0e.appspot.com',
    iosBundleId: 'com.example.flutterExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWQtv910LSQLpHLh_QkfT2blPw7anpIms',
    appId: '1:938205689320:web:cb79943cd8558c22eee05d',
    messagingSenderId: '938205689320',
    projectId: 'examflutter-9bb0e',
    authDomain: 'examflutter-9bb0e.firebaseapp.com',
    storageBucket: 'examflutter-9bb0e.appspot.com',
  );
}
